# Use postgres/example user/password credentials
services:
  db:
    image: postgres:16
    container_name: dec-postgres
    restart: no
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "127.0.0.1:5432:5432"
    expose:
      - 5432
    volumes:
      - db-home:/root
      - db-data:/var/lib/postgresql/data

volumes:
  db-home:
  db-data:
